name: Build & Publish Visual Studio Extension

on:
  push:
    branches: [main]
    tags: ['v*']          # same trigger as the VS Code workflow

jobs:
  vsix:
    runs-on: windows-latest
    env:
      CONFIGURATION: Release

    steps:
    - uses: actions/checkout@v4
    
    - name: Add nuget to PATH
      uses: nuget/setup-nuget@v1

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    # ── Build language-server for win-x64 only ───────────────────────
    - name: Publish LSP (win-x64)
      shell: bash
      run: |
        OUT="GameScript.VisualStudio/Server/win-x64"
        mkdir -p "$OUT"
        dotnet publish \
          GameScript.LanguageServer/GameScript.LanguageServer.csproj \
          -c Release -r win-x64 --self-contained true \
          -p:PublishSingleFile=true -o "$OUT"
          
    - name: Restore
      run: nuget restore

    # ── Build Visual Studio extension (.vsix) ────────────────────────
    - name: Build VSIX
      run: |
        msbuild GameScript.VisualStudio/GameScript.VisualStudio.csproj `
          -p:Configuration=$env:CONFIGURATION -p:DeployExtension=false -p:ZipPackageCompressionLevel=normal

    - name: Locate VSIX
      id: find_vsix
      run: |
        $vsix = Get-ChildItem -Path GameScript.VisualStudio -Filter *.vsix -Recurse `
                | Select-Object -First 1
        echo "path=$($vsix.FullName)" >> $env:GITHUB_OUTPUT

    # ──────────────────────────────────────────────
    # Publish to Visual Studio Marketplace
    # ──────────────────────────────────────────────
    - name: Publish extension to Marketplace
      uses: cezarypiatek/VsixPublisherAction@1.1
      with:
        extension-file: GameScript.VisualStudio/bin/Release/GameScript.VisualStudio.vsix
        publish-manifest-file: GameScript.VisualStudio/publishManifest.json
        personal-access-code: ${{ secrets.VSIX_PUBLISHER_TOKEN }}